### ISSUE TITLE
Does not work on IE11

### ISSUE THREAD

**Issue by Gouigouix** [leandrosimoes/ls-countdown#3]
Hi @leandrosimoes,

Can you add an export in ES5 to make the API available on Internet Explorer 11. He can not interpret the Classes; o)

Thx,
John.

**Comment by leandrosimoes** [comment]
> Hi @leandrosimoes,
> 
> Can you add an export in ES5 to make the API available on Internet Explorer 11. He can not interpret the Classes; o)
> 
> Thx,
> John.

Hi @Gouigouix ,

Sure, I'll do that asap and let you know.

**Comment by Gouigouix** [comment]
@leandrosimoes very nice thank you ;o)

**Comment by leandrosimoes** [comment]
@Gouigouix I just merged and publish a new version to npm too. Could you please check if everything is working. I'll close this issue but if anything goes wrong you can feel free to repopen. Thanks!

**Comment by Gouigouix** [comment]
Thank you @leandrosimoes it's working very well ;)

**Comment by leandrosimoes** [comment]
> Thank you @leandrosimoes it's working very well ;)

Good to know! Thanks!
